services:
  postgres:
    extends:
      file: postgres.yml
      service: postgres

  elasticsearch:
    extends:
      file: elasticsearch.yml
      service: elasticsearch

  kibana:
    extends:
      file: kibana.yml
      service: kibana

volumes:
  postgres_data:
    name: postgres_data
    driver: local
  elastic_data:
    name: elastic_data
    driver: local

networks:
  dev-net:
    name: dev-net
    driver: bridge