version: '3.8'

services:
  datadog:
    image: gcr.io/datadoghq/agent:latest
    container_name: datadog
    env_file:
      - ../.env
    environment:
      DD_API_KEY: ${DD_API_KEY}
      DD_SITE: ${DD_SITE}
    ports:
      - "8126:8126"
