services:
  datadog:
    extends:
      file: datadog.yml
      service: datadog

volumes:
  datadog_logs:  # ✅ Explicitly defining volume for Datadog (if needed)
    name: datadog_logs
    driver: local