services:
  auth-db:
    extends:
      file: postgres.yml
      service: auth-db

  redis:
    extends:
      file: redis.yml
      service: redis

  elasticsearch:
    extends:
      file: elasticsearch.yml
      service: elasticsearch

  kibana:
    extends:
      file: kibana.yml
      service: kibana

volumes:
  postgres_data:
    name: postgres_data
    driver: local

  redis_data:
    name: redis_data
    driver: local

  elastic_data:
    name: elastic_data
    driver: local

networks:
  elk:
    name: elk
    driver: bridge