services:
  auth-db:
    extends:
      file: postgres.yml
      service: auth-db

  redis:
    extends:
      file: redis.yml
      service: redis

volumes:
  auth_postgres_data:  # ✅ Explicitly defining volume
    name: auth_postgres_data
    driver: local

  auth_redis_data:  # ✅ Explicitly defining volume for Redis
    name: auth_redis_data
    driver: local