version: '3.8'

services:
  auth-db:
    image: mysql:8
    container_name: auth-db
    restart: always
    env_file:
      - ../.env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - auth_mysql_data:/var/lib/mysql

volumes:
  auth_mysql_data:
    driver: local